### PR TITLE
Module5:Budget-app

### PR DESCRIPTION
**Pull request by derrick1451**
### Requirements
- Splash screen

  - A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.
  - Sign up and log in pages

- The user should be able to register in the app with full name, email and password (all mandatory).
- The user can log into the app using email and password.
  - If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).
  - Home page (categories page)

- When the user logs in, they are presented with the categories page.
- For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
- When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
- There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
Transactions page

- For a given category, the list of transactions is presented, ordered by the most recent.
- At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
- There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- When the user clicks on the "Back" button (<), the user navigates to the home page.
- "Add a new category" page

- The user fills out a form to create a new category, indicating their name and icon (both mandatory).
- The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
- When the user clicks on the "Back" button (<), the user navigates to the home page.
- "Add a new transaction" page

- The user fills out a form to create a new transaction with:
 - name (mandatory)
  - amount (mandatory)
- categories (mandatory at least one)
- The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
- When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.
[Testing requirements](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#testing-requirements)
- Create unit and integration tests for all the most important components of your RoR application.
[Technical requirements](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#technical-requirements)
- You should use Postgres as your database.
- You should use devise for authentication.
- You should validate all user input to make sure that anyone with bad intentions cannot compromise your app.
- You can use a view template engine of your choice (.erb, .slim, .haml).
- The project should be deployed and accessible online.
- Your database schema should reflect the following structure:
### Highlights
RESOLVED

### CODE REVIEW

**Review by laiifuu — COMMENTED** [review]
# STATUS: INVALID :stop_sign: 

## Hi @derrick1451  :wave:  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

c60b0c9f441f523e67e64afc52bec690

## Invalid Code Review Request

You have submitted a project where  the PR is created from a feature branch that does not hold all the changes made to the project, therefore the project's files cannot be accessed in the `files changed` section.
You should ask for a review using a PR where you compare a feature branch that holds all the changes made with the development branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and :computer: Happy coding :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by prolajumokeoni — APPROVED** [review]
Hi @derrick1451,  I am currently reviewing your project are you available for a quick call?
-  when I run your tests some are failing in my local machine

Screenshot_201

**Comment by derrick1451** [comment]
@prolajumokeoni yes l am

**Comment by prolajumokeoni** [comment]
> @prolajumokeoni yes l am

please check your slack @derrick1451

**Comment by derrick1451** [comment]
> > @prolajumokeoni yes l am
> 
> please check your slack @derrick1451

am done running the tests and they are passing could l share my screen on slack such that you could see  them

**Comment by prolajumokeoni** [comment]
Hi @derrick1451, you can call me on slack

**Review by prolajumokeoni — APPROVED** [review]
Hi @derrick1451 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Deployed app link works correctly ✅ 
 - List of transactions is presented ordered by the most recent 👏🏿 
 - Your app design matches the original design 🥇  
 - Devise used for authentication 💪🏿 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
